# Generated by Django 4.2.5 on 2023-09-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('b_day', models.DateField()),
                ('image', models.ImageField(upload_to='images/authors')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('pages', models.IntegerField(verbose_name='Pages')),
                ('image', models.ImageField(upload_to='images/books')),
                ('author', models.ManyToManyField(related_name='books', to='giveaway.author')),
                ('condition', models.ManyToManyField(related_name='books', to='giveaway.condition')),
                ('genre', models.ManyToManyField(related_name='books', to='giveaway.genre')),
            ],
        ),
    ]
